.circleci/config.yml: total redo, using if/then with check_formatting_exit_status var for exit code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -40,9 +40,18 @@ jobs:
       - run:
           name: Check formatting
           command: |
-            result="$( docker-compose run backend-test /bin/bash -c 'export APP_PATH=/app/; if [[ ! -z $( find $APP_PATH -name "*.go" ) ]]; then gofmt -l $APP_PATH; else echo >&2 "No *.go files found in path: $APP_PATH"; fi' )"
-            echo "DEBUG: '$result'"
-            test -z "$result"
+            gofmt_result="$( docker-compose run backend-test /bin/bash -c 'export APP_PATH=/app/; if [[ ! -z $( find $APP_PATH -name "*.go\
+            " ) ]]; then gofmt -l $APP_PATH; else echo >&2 "No *.go files found in path: $APP_PATH"; fi' )"
+
+            if [ -z "$gofmt_result" ]
+            then
+                check_formatting_exit_status=0
+            else
+                echo -e "gofmt check fail:\n$gofmt_result"
+                check_formatting_exit_status=1
+            fi
+
+            exit $check_formatting_exit_status
       - run:
           name: Run tests
           command: |
